// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }




//huzzl
  //   static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyAlDCY6OBK4zRlLafxjyG__thsdWZML2CU',
  //   appId: '1:764873088756:web:8966d144e2f5584fb6c8a1',
  //   messagingSenderId: '764873088756',
  //   projectId: 'huzzl-proj',
  //   authDomain: 'huzzl-proj.firebaseapp.com',
  //   storageBucket: 'huzzl-proj.appspot.com',
  // );
  
//huzzl02
  // static const FirebaseOptions web = FirebaseOptions(
  //  apiKey: "AIzaSyCZI7RKKwX4a8yS22oZJS85g3mfKtSkfo8",
  // authDomain: "huzzl02.firebaseapp.com",
  // projectId: "huzzl02",
  // storageBucket: "huzzl02.firebasestorage.app",
  // messagingSenderId: "407897970861",
  // appId: "1:407897970861:web:597143bd7532939df9ce24"
  // );

  //huzzl03
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyC1VUjgmRO6d-wax6LU3254lU-g2GKIY10",
  authDomain: "huzzl03.firebaseapp.com",
  projectId: "huzzl03",
  storageBucket: "huzzl03.firebasestorage.app",
  messagingSenderId: "266369978822",
  appId: "1:266369978822:web:b4088eed07bbc8999d22c7"  );
}
